export default [
  [
    ['Hello traveller. Welcome to la Sorbonne.', 0],
    ['Today, you have the chance to', 3000],
    ['discover the surprising story of this famous building.', 6000],
    ['', 10000]
  ],
  [
    ['Among the thousands students that came to La Sorbonne,', 0],
    ['Richelieu is of the most famous one.', 3000],
    ['Famous minister of Louis the XIII,', 6000],
    ['religious man, cleaver, ambitious,', 8000],
    ['Armand Jean du Plessis de Richelieu', 11000],
    ['was born in 1585 in a huge sibling.', 13500],
    ['Promised to a war future,', 18300],
    ['he finally assumed the role of bishop of Luçon.', 19400],
    ['As a responsible man,', 22700],
    ['the cardinal has also been head teacher of La Sorbonne,', 24600],
    ['several years later...', 27500],
    ['His strong will to reinforce the king’s power', 29600],
    ['lead to authority resurgence,', 32600],
    ['now called “absolutism”.', 34500],
    ['Here is our young Richelieu, in 1606,', 37300],
    ['during its arrival at La Sorbonne,', 41100],
    ['in front of the gates of the medieval chapel.', 42700],
    ['Have a look at those stained-glasses', 46300],
    ['that, for a change, does not represent a biblical scene.', 48400],
    ['It tells us a different story,', 51800],
    ['especially anormal...', 54200],
    ['The story… of a skull.', 56800],
    ['An important skull...', 59300],
    ['', 62000]
  ],
  [
    ['Well… Wat is this fuss about ?', 0],
    ['Those people do not look like clerics', 2300],
    ['or students here to pay their respects !', 4300],
    ['So who are they ?', 7000],
    ['Young Richelieu can’t imagine it,', 8800],
    ['but you may have recognize them...', 11600],
    ['They are the protestors of 1789 called', 13500],
    ['the “sans-culottes” !', 17800],
    ['They have come to desecrate the tomb.', 20000],
    ['But who does it belong to ?', 22000],
    ['Who could deserve such a fate...?', 24500],
	  ['', 28000]
  ],
  [
    ['Some people says that the skull', 0],
    ['quickly found new owners :', 2000],
    ['young children, using it as a ball to play !', 5000],
    ['An abbot, seeing them, would have played with them.', 9000],
    ['', 13000]
  ],
  [
    ['He would have also taken the head with him,', 0],
    ['once his young friends got bored of the relic.', 3000],
    ['The theft committed by the abbot Baschamp', 5900],
    ['is a possible option, but, don’t worry,', 8000],
    ['the tale of the skull used as a ball is just a legend !', 10200],
    ['However, this legend was told so many times', 14500],
    ['that many people believed it was true for several years !', 17000],
	  ['', 19500]
  ],
  [
    ['Another version of the story exists.', 0],
    ['An inhabitant would have seen to sinister spectacle of the desecration.', 2700],
    ['Horrified, he would have taken', 6900],
    ['and protected the skull in a piece of shroud...', 9300],
    ['In truth, it was an hosier called Cheval,', 12800],
    ['living a few streets away from La Sorbonne.', 16700],
    ['He succeeded to secure the skull', 19500],
    ['and preserve it from a disastrous destiny...', 21900],
	  ['', 24500]
  ],
  [
    ['It seems that we left Paris !', 0],
    ['Are we going to follow the adventures of the skull from town to town ?', 3200],
    ['Once in possession of the hosier Cheval,', 7200],
    ['the relic seem to totally disappear.', 9300],
    ['Many people thought the relic was lost, some have said it destroyed.', 12000],
    ['The truth is,', 16200],
    ['the skull travelled far from Paris and La Sorbonne.', 17800],
    ['It even went to Brittany !', 21800],
	  ['', 24500]
  ],
  [
    ['Kept in a safe place by the hosier Cheval,', 0],
    ['it was then confided to the priest Nicolas Armez and his family, since 1805.', 2800],
    ['Passed down from one generation to the next,', 9500],
    ['the priest’s family preserved the relic during almost 60 years !', 12000],
	  ['', 17500]
  ],
  [
    ['The skull was kept with great care.', 0],
    ['A pharmacist ensure its proper preservation,', 2800],
    ['applying an anti-bug treatment and even a varnish !', 5200],
    ['Why paying so much attention ?', 9500],
	  ['', 12000]
  ],
  [
    ['Despite the quality of the treatment,', 0],
    ['the head seems to be the heart of a surprising ceremony :', 2500],
    ['the relic was exposed for all to see once a year...', 5500],
    ['Its affront was finally reached the ears of the emperor Napoleon the Third.', 9300],
    ['He ordered the return of the skull to its final resting place, in 1866.', 13000],
    ['And now the emperor got involve...', 18000],
    ['the deceased appears to be of particular importance...', 19700],
	  ['', 24000]
  ],
  [
    ['After a long trip during more than 70 years,', 0],
    ['the skull came back to its mausoleum,', 3400],
    ['ready to rest in peace, for good.', 6200],
    ['What a surprise, for young Richelieu,', 9000],
    ['to discover the place of his tomb.', 11500],
    ['This is his college...', 14300],
    ['The place he is standing right now.', 16400],
	  ['', 19500]
  ],
  [
    ['On close inspection,', 0],
    ['the tomb really looks like...', 2300],
    ['the one it is built for...', 4600],
    ['This is the story of the cardinal’s burial...', 7300],
    ['Richelieu, after becoming head teacher at La Sorbonne,', 11400],
    ['will finance the construction of the new college’s church', 15000],
    ['where he wants to be buried.', 18400],
    ['The cardinal will die in 1642,', 21000],
    ['but the tomb he desired', 24000],
    ['will only be achieved in 1694 par the sculptor Girardon,', 26200],
    ['commissioned by Richelieu’s niece :', 30600],
    ['Marie-Madeleine d’Aiguillon.', 33000],
    ['', 35000]
  ],
  [
    ['Young Richelieu is not out of the wood,', 0],
    ['because the story of the skull, his… skull,', 3700],
    ['appears to continue.', 6400],
    ['A second desecration happened...', 8500],
    ['This one seems less violent :', 14000],
    ['a small group is busy around the relic,', 16400],
    ['with curiosity.', 19000],
    ['There is even a man observing the head,', 21400],
    ['through a strange telescope...', 23600],
    ['A cubic one...?', 26000],
    ['This second desecration took place the 25th of June 1895,', 29100],
    ['thanks to Gabriel Hanotaux, foreign minister.', 33700],
    ['This small group had the purpose of photograph the relic,', 38300],
    ['making mouldings of it...', 41600],
    ['Once their business done,', 44300],
    ['the tomb was finally closed,', 46400],
    ['and never been disturbed again.', 48900],
	  ['', 52500]
  ]
]